PRIJS_CROISSANT = 0.39
AANTAL_STOKBROOD = 17

PRIJS_STOKBROOD = 2.78 
AANTAL_STOKBROOD = 2

PRIJS_KORTINGSBON = 0.50
AANTAL_KORTINGSBON = 3

totaal_croissant = AANTAL_STOKBROOD * PRIJS_CROISSANT 
totaal_stokbrood = PRIJS_STOKBROOD * AANTAL_STOKBROOD
totaal_kortingsbon = PRIJS_KORTINGSBON * AANTAL_KORTINGSBON
TOTAAL = totaal_croissant + totaal_stokbrood - totaal_kortingsbon
print(TOTAAL)
