naam = input('hallo wat is je naam? ')
leeftijd = input(f'Goedendag {naam}, hoe oud ben je? ')
eten = input(f'en als {leeftijd} jarige, wat eet je het liefst? ')
drinken = input(f'en wat drink je het liefst bij {eten}? ')
print()
print(f'De {leeftijd} jarige {naam} drinkt het liefst {drinken} bij {eten}')